### ISSUE TITLE
Clean up organization of project, starting with lsp-zero

### ISSUE THREAD

**Issue by trevor-utilityapi** [trevorhauter/nvtrev2#13]
In general, I think we should probably store as much of the configuration for our plugins as possible in each of the plugin files in the plugin directory. For lsp-zero, the lsp config must live in the config directory, but, for the keybindings as well as the function to disable es-lint, I think that could be stored in the lsp-zero plugin file

**Comment by trevorhauter** [comment]
This is pretty broad, and I might not ever actually do it. Closing for now.
