### ISSUE TITLE
Find a plugin that gives you context in your position in a python file

### ISSUE THREAD

**Issue by trevor-utilityapi** [trevorhauter/nvtrev2#18]
When I'm in a python file, particularly a giant class or function where I can't see the top, I'd like some indicator to my location. I'd like to know, whithout painfully scrolling to the top, where I am

**Comment by trevorhauter** [comment]
Omg I finally found it!

**Comment by trevorhauter** [comment]
https://github.com/trevorhauter/nvtrev2/commit/1fc8db8b818a9de707b5f8a82299d0a441ffe56d
