### ISSUE TITLE
Is the bespoke solution for nvim-trees autowidth problems bad?

### ISSUE THREAD

**Issue by trevor-utilityapi** [trevorhauter/nvtrev2#26]
https://github.com/trevorhauter/nvtrev2/blob/main/lua/plugins/nvim-tree.lua#L1-L19

After using it I'm realizing there is a very high chance we can just configure this through nvim-tree and get rid of the added complexity. Let's take a look into this!

**Comment by trevorhauter** [comment]
Yes, it's so horrible lol. Why did I do this? I think I used chatgpt to do this, it's when I was still learning everything. What a disaster. Should have trusted google!
https://www.reddit.com/r/neovim/comments/14ctw60/how_to_have_nvimtree_fit_all_elements_to_the_view/

**Comment by trevorhauter** [comment]
Fixed in this commit btw https://github.com/trevorhauter/nvtrev2/commit/f34154739e99512265d1af49f17a1d4461b764fb
